### ISSUE TITLE
any plan to render into configmap instead of secret?

### ISSUE THREAD

**Issue by zhoushuke** [machinezone/configmapsecrets#2]
This project is what I was searching for, but I think it is more reasonable to generate the configmap in the end,so I can view it from rancher(a kind of container platform which can't show crd in front web) UI without using base64 to decode to see content. it's more more convenient. 
for example, It can provide a field(eg. cms.Spec.targetType: configmap) to specify it is generated secret or configmap, if no given, default secret. any plan to support?

**Comment by abursavich** [comment]
No, sorry for the inconvenience, but I think your issue is with the Rancher UI.

ConfigMapSecrets exists for the sole purpose of merging public (configmap) data and private (secret) data. Its design should not compromise the secrecy of the private data.
