### ISSUE TITLE
Allow for running in namespaces other than kube-system

### ISSUE THREAD

**Issue by Niksko** [machinezone/configmapsecrets#6]
Thanks for writing this, it perfectly solves the conundrum of how to manage secrets within alertmanager without having to put all of your config in a secret.

I tried to install this in a namespace other than `kube-system`, and it fails because it seems to be trying to create a leader election `configMap` in `kube-system`.

Could you please allow installation of this into a namespace other than `kube-system`? Simplest method might just be to use an env variable like `POD_NAMESPACE` that defaults to `kube-system`, and then let people configure it themselves at installation time using the downward API?

**Comment by abursavich** [comment]
If you run the controller in "local" mode (`--all-namespaces=false`) with leader election enabled (`--enable-leader-election`), then it will only watch objects in its own namespace which it will use for leader election.

If you run the controller in "global" mode (`--all-namespaces`) with leadership election enabled (`--enable-leader-election`), then it will watch objects in all namespaces and use the `kube-system` namespace for leader election.

The theory behind forcing `kube-system` in "global" mode is to prevent "global" controllers installed in multiple namespaces from thrashing, but perhaps this is too paternalistic. If you're trusted to grant RBAC access to the whole cluster, you should probably be trusted not to run multiple "global" controllers with different leader election configs. I'll think about adding more knobs for controlling leadership election.

In the meantime, you can run in "local" mode or disable leader election (using only 1 replica) in "global" mode.

**Comment by abursavich** [comment]
Closed with https://github.com/machinezone/configmapsecrets/commit/3ef11dbb71eda905f40deef0e9be025ce22bb4a4 and cut release [v0.4.0](https://github.com/machinezone/configmapsecrets/releases/tag/v0.4.0).
